name: Build artifact

on: push

jobs:
  Build_artifact:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.14
      options: --entrypoint=sh
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add texmf-dist-latexextra
          apk add make

      - name: Compile with makefile
        run: make

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: output/tesi.pdf
