name: Build and release artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y texlive texlive-latex-extra texlive-lang-italian
          wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
          sudo dpkg -i pandoc-2.14.1-1-amd64.deb

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile with makefile
        run: make

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: output/tesi.pdf
      
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: output/tesi.pdf
