name: Compile and publish thesis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y texlive texlive-latex-extra texlive-lang-italian
          wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
          dpkg -i pandoc-2.14.1-1-amd64.deb

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile with makefile
        run: make

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: output/tesi.pdf
